In [37]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [3]:
data = pd.read_csv('./data/X_train.csv')

In [9]:
colonne = []
for i in range(1000):
    colonne.append('holed_' + str(i+1))
df = data.drop(columns=colonne)
holed = data[colonne]
holed_copy = holed.copy()
df

,Horodate,5423908671,2568793410,8310762594,6235194807,423895617,193845276,216589743,218753964,1794650328,...,2187645930,6502938147,9185760234,4972518063,9638012547,294387516,271684359,2967158034,1973824650,9625401873
0,2023-01-09 00:00:00,352.0,0.0,371.0,110.0,724.0,102.0,256.0,7.0,105.0,...,308.0,245.0,185.0,95.0,210.0,90.0,66.0,265.0,28.0,1058.0
1,2023-01-09 00:30:00,405.0,0.0,363.0,108.0,478.0,147.0,281.0,8.0,134.0,...,1097.0,235.0,188.0,81.0,143.0,74.0,73.0,195.0,30.0,1298.0
2,2023-01-09 01:00:00,599.0,0.0,352.0,93.0,832.0,155.0,295.0,5.0,96.0,...,2486.0,222.0,256.0,86.0,139.0,75.0,53.0,201.0,52.0,1049.0
3,2023-01-09 01:30:00,315.0,0.0,348.0,84.0,574.0,152.0,267.0,15.0,156.0,...,1010.0,223.0,200.0,86.0,642.0,397.0,47.0,196.0,61.0,704.0
4,2023-01-09 02:00:00,448.0,0.0,364.0,73.0,421.0,176.0,346.0,38.0,97.0,...,258.0,214.0,202.0,86.0,354.0,602.0,44.0,216.0,55.0,1033.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1052,2023-01-30 22:00:00,556.0,0.0,879.0,84.0,989.0,236.0,751.0,0.0,1027.0,...,282.0,279.0,283.0,402.0,161.0,160.0,102.0,1023.0,48.0,1159.0
1053,2023-01-30 22:30:00,468.0,0.0,982.0,89.0,1866.0,213.0,741.0,0.0,1116.0,...,548.0,277.0,260.0,460.0,69.0,147.0,94.0,543.0,51.0,583.0
1054,2023-01-30 23:00:00,503.0,0.0,769.0,94.0,1696.0,222.0,699.0,0.0,979.0,...,433.0,281.0,278.0,325.0,76.0,120.0,88.0,317.0,56.0,578.0
1055,2023-01-30 23:30:00,442.0,0.0,600.0,83.0,1852.0,220.0,678.0,0.0,564.0,...,453.0,283.0,209.0,935.0,83.0,56.0,94.0,255.0,34.0,650.0
1056,2023-01-31 00:00:00,506.0,0.0,463.0,88.0,1095.0,188.0,688.0,0.0,356.0,...,345.0,283.0,202.0,624.0,71.0,91.0,80.0,160.0,46.0,677.0

In [14]:
# Méthode de régression linéaire
date = df.columns[0]
df[date] = pd.to_datetime(df[date])
df["date"] = (df[date] - df[date].min()).dt.total_seconds()
model = LinearRegression()
for col in holed.columns:
    inter = pd.concat([df[["date"]], holed[col]], axis=1).dropna()
    model.fit(inter[["date"]], inter[col])
    pred = model.predict(df[["date"]])
    holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
holed

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  holed[col] = holed[col].fillna(pd.Series(pred, index=holed.index))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\469699880.py:10: SettingWithCopyWarning:

,holed_1,holed_2,holed_3,holed_4,holed_5,holed_6,holed_7,holed_8,holed_9,holed_10,...,holed_991,holed_992,holed_993,holed_994,holed_995,holed_996,holed_997,holed_998,holed_999,holed_1000
0,578.000000,698.0,5.00764,2.000000,283.000000,154.0,131.0,619.0,107.000000,466.000000,...,0.0,32.0,152.000000,511.619460,0.0,1099.0,117.0,45.0,253.000000,186.000000
1,533.000000,224.0,18.00000,2.000000,1047.000000,150.0,106.0,542.0,114.000000,913.648287,...,0.0,34.0,84.000000,511.756873,0.0,782.0,109.0,40.0,227.000000,180.000000
2,623.000000,246.0,17.00000,188.473312,1185.000000,131.0,74.0,517.0,109.000000,547.000000,...,0.0,30.0,24.000000,511.894286,0.0,630.0,375.0,58.0,237.000000,166.000000
3,613.000000,643.0,17.00000,18.000000,746.000000,77.0,146.0,455.0,244.718622,390.000000,...,0.0,34.0,24.000000,512.031699,0.0,773.0,468.0,48.0,245.000000,525.000000
4,1823.000000,318.0,18.00000,15.000000,560.000000,125.0,82.0,551.0,104.000000,534.000000,...,0.0,30.0,46.000000,512.169111,0.0,879.0,534.0,41.0,175.000000,372.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1052,818.103620,470.0,79.00000,0.000000,344.000000,38.0,237.0,784.0,228.000000,2111.000000,...,0.0,19.0,30.000000,115.000000,0.0,1696.0,142.0,86.0,219.220975,347.229703
1053,818.054698,960.0,52.00000,0.000000,160.000000,52.0,250.0,495.0,248.000000,2049.000000,...,0.0,18.0,45.837194,126.000000,0.0,1727.0,94.0,88.0,219.419101,347.322013
1054,818.005775,1102.0,127.00000,0.000000,840.370229,50.0,223.0,541.0,204.000000,1749.000000,...,0.0,18.0,45.847735,113.000000,0.0,1575.0,143.0,94.0,219.617226,151.000000
1055,665.000000,90.0,15.00000,0.000000,292.000000,68.0,269.0,539.0,123.000000,2391.000000,...,0.0,18.0,237.000000,107.000000,0.0,1301.0,111.0,63.0,219.815352,363.000000
1056,677.000000,371.0,12.00000,0.000000,74.000000,66.0,181.0,622.0,109.000000,414.000000,...,0.0,17.0,217.000000,109.000000,0.0,1319.0,74.0,45.0,328.000000,187.000000

In [16]:
y_train = pd.read_csv('./data/y_train.csv')
y_train_clean = y_train.drop(columns=['Horodate'])
y_train_clean = y_train_clean.fillna(0)
mae = mean_absolute_error(y_train_clean.to_numpy().flatten(), holed.to_numpy().flatten())
print(f"MAE sur l'entraînement : {mae}")
print(model.score(df[["date"]], holed[col]))

MAE sur l'entraînement : 14.970880725446289
0.09631046268811927

In [47]:
def fill_nan_with_interpolation_linear(column):
    col = column.copy()
    col = col.interpolate(method='linear', limit_direction='both')
    return col

In [ ]:
y_pred = holed_copy.apply(fill_nan_with_interpolation_linear, axis=0)

mae_benchmark = mean_absolute_error(y_train_clean.to_numpy().flatten(), y_pred.to_numpy().flatten())
print(f"MAE benchmark : {mae_benchmark}")

MAE benchmark : 12.428300483575784

In [39]:
def fill_nan_with_interpolation_spline(column):
    col = column.copy()
    col = col.interpolate(method='spline', limit_direction='both',order=3)
    return col

In [41]:
df_test = pd.read_csv('./data/X_test.csv')

In [42]:
colonne = ["Horodate"]
for i in range(1000):
    colonne.append('holed_' + str(i+1))
#df_test = df_test.drop(columns=colonne)
holed_test = df_test[colonne]
y_test_pred = holed_test.apply(fill_nan_with_interpolation_spline, axis=0)
#y_test_pred.to_csv('./data/y_test.csv',index=False)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\1051977742.py:3: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  col = col.interpolate(method='spline', limit_direction='both',order=3)
c:\Users\Lenovo\anaconda3\Lib\site-packages\pandas\core\missing.py:604: UserWarning:
The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.
There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  terp = interpolate.UnivariateSpline(x, y, k=order, **kwargs)

In [43]:
y_test_pred_clean = y_test_pred.drop(columns=['Horodate'])
erreur = mean_absolute_error(y_train_clean.to_numpy().flatten(), y_test_pred_clean.to_numpy().flatten())
print(f"MAE sur le test : {erreur}")

MAE sur le test : 4445970203.7791195

In [46]:
y_test_pred = holed_test.apply(fill_nan_with_interpolation_linear, axis=0)
y_test_pred_clean = y_test_pred.drop(columns=['Horodate'])
erreur = mean_absolute_error(y_train_clean.to_numpy().flatten(), y_test_pred_clean.to_numpy().flatten())
print(f"MAE sur le test (interpolation linéaire) : {erreur}")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5188\4098200023.py:3: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  col = col.interpolate(method='linear', limit_direction='both')

MAE sur le test (interpolation linéaire) : 410.8660654020999